name: Build and deploy on push

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          submodules: "recursive"

      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: docs
          TOKEN: ${{ secrets.INTERNALS_TOKEN }}
          BUILD_FLAGS: --drafts
